version: '2.18'
services:
  server:
    build: ./server
    container_name: nighthawk_server_c
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: nighthawk_client_c
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true